
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
// change number one
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Дима
 */
public class InteractivePercolationForm extends javax.swing.JFrame {

    /**
     * Creates new form InteractivePercolationForm
     */
    public InteractivePercolationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        RadioButton2D = new javax.swing.JRadioButton();
        RadioButton3D = new javax.swing.JRadioButton();
        SizeOfField = new javax.swing.JTextField();
        NumberOfIterations = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        logFile = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RadioButton2D.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RadioButton2D.setText("2D");
        RadioButton2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton2DActionPerformed(evt);
            }
        });

        RadioButton3D.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RadioButton3D.setText("3D");
        RadioButton3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton3DActionPerformed(evt);
            }
        });

        SizeOfField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SizeOfField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SizeOfFieldActionPerformed(evt);
            }
        });

        NumberOfIterations.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Число итераций");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ширина поля");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Test");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(logFile);

        jLabel3.setText("Дата, Кол-во измерений, Ширина поля, Число итераций, Продолжительность измерения, Граничная вероятность, Версия программы");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioButton2D)
                            .addComponent(RadioButton3D))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(SizeOfField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NumberOfIterations, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButton2D)
                    .addComponent(SizeOfField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButton3D)
                    .addComponent(NumberOfIterations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public int Dimension;
    public String version = "version 1.0";

    private void RadioButton3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton3DActionPerformed
        // TODO add your handling code here:
        Dimension = 3;
    }//GEN-LAST:event_RadioButton3DActionPerformed

    private void TestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestButtonActionPerformed
        // TODO add your handling code here:
        int N, i;
        
        try {
            N = Integer.parseInt(
                this.SizeOfField.getText());
        } 
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Bad first number",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            i = Integer.parseInt(
                this.NumberOfIterations.getText());
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Bad second number",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
       if ( Dimension == 3 ){
        double timeout= System.currentTimeMillis();
        PercolationStats3D ps = new PercolationStats3D(N, i);
        timeout = System.currentTimeMillis() - timeout;
        String text = logFile.getText();
        try{
        FileOutputStream fout = new FileOutputStream("G:\\logfile.txt", true);
        BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(fout));                 
            try{    
                bw.newLine();
                bw.write(text);
                bw.close();
            }
            catch(IOException e){}
        }
        catch(FileNotFoundException e) {JOptionPane.showMessageDialog(null,"Такого файла нет!","Произошла ошибка", JOptionPane.ERROR_MESSAGE);}
        Date d = new Date();
        SimpleDateFormat format1 = new SimpleDateFormat("dd.MM.yyyy hh:mm");
        System.out.println(format1.format(d));
        logFile.setText(text + "\n"
              + format1.format(d)
              + "," + Dimension + "D"
              + "," + N
              + "," + i
              + "," + timeout/1000
              + "," + ps.mean() + "," 
              + version);}
       
       
        if ( Dimension == 2 ){
        double timeout= System.currentTimeMillis();
        PercolationStats2D ps = new PercolationStats2D(N, i);
        timeout = System.currentTimeMillis() - timeout;
        String text = logFile.getText();
        try{
        FileOutputStream fout = new FileOutputStream("G:\\logfile.txt", true);
        BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(fout));                 
            try{    
                bw.newLine();
                bw.write(text);
                bw.close();
            }
            catch(IOException e){}
        }
        catch(FileNotFoundException e) {JOptionPane.showMessageDialog(null,"Такого файла нет!","Произошла ошибка", JOptionPane.ERROR_MESSAGE);}
        Date d = new Date();
        SimpleDateFormat format1 = new SimpleDateFormat("dd.MM.yyyy hh:mm");
        System.out.println(format1.format(d));
        logFile.setText(text
              + format1.format(d)
              + "," + Dimension + "D"
              + "," + N
              + "," + i
              + "," + timeout/1000
              + "," + ps.mean() + "," 
              + version + "\n");}
    }//GEN-LAST:event_TestButtonActionPerformed

    private void SizeOfFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SizeOfFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SizeOfFieldActionPerformed

    private void RadioButton2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton2DActionPerformed
        // TODO add your handling code here:
        Dimension = 2;
    }//GEN-LAST:event_RadioButton2DActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InteractivePercolationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InteractivePercolationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InteractivePercolationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InteractivePercolationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InteractivePercolationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NumberOfIterations;
    private javax.swing.JRadioButton RadioButton2D;
    private javax.swing.JRadioButton RadioButton3D;
    private javax.swing.JTextField SizeOfField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane logFile;
    // End of variables declaration//GEN-END:variables
}
